#!/usr/bin/python

# Copyright 2016 Tomasz Rozbicki
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import subprocess

if sys.argv[1] == "-h":
  print "Place cursor in the text input field on your Android device. The field will be completed automatically by the script."
  exit()

if len(sys.argv) < 2:
  print "Usage: adb-type TEXT"
  exit(1)

command = "adb shell input text %s" % (sys.argv[1])
subprocess.Popen(['bash', '-c', command])
